### ISSUE TITLE
Remove the first citation 49 since it fits the whole paragraph with one citation at the end. 

### ISSUE THREAD

**Issue by AlexanderTitus** [In-Vivo-Group/generative-biology#39]
Community computing platforms democratized participation and expanded bioinformatics research’s reach. Platforms like BOINC [[49](https://in-vivo-group.github.io/generative-biology/#ref-1BWjfloX3)] enabled broad participation in bioinformatics. Experts can submit computing tasks to BOINC, while non-experts and science enthusiasts can volunteer their computer resources to process these tasks. Several life sciences projects are available through BOINC, including protein-ligand docking, malaria simulations, and protein folding [[49](https://in-vivo-group.github.io/generative-biology/#ref-1BWjfloX3)].

**Comment by samadon1** [comment]
Fixed ✅
