### ISSUE TITLE
Citation 66/67

### ISSUE THREAD

**Issue by AlexanderTitus** [In-Vivo-Group/generative-biology#40]
Based on the given problem and the available data, there are many potential model and training paradigms, three of the most prominent types of ML being: supervised learning [[66](https://in-vivo-group.github.io/generative-biology/#ref-117qAPYe7)], unsupervised learning [[url?](https://in-vivo-group.github.io/generative-biology/#ref-url) https://www.ncbi.nlm.nih.gov/pmc/articles/PMC5765025,[67](https://in-vivo-group.github.io/generative-biology/#ref-bLNWjb9u)],

**Comment by samadon1** [comment]
Fixed ✅
